### PR TITLE
Use GB18030 instead of GB2312

### PR DESCRIPTION
**Pull request by rlue**
`rchardet` erroneously detects "GB2312" for some strings:

```ruby
>> str = "\xA8D\xB3\xC2\xD6\xBE"
=> "\xA8D\xB3\xC2־"
>> str.encoding
=> #<Encoding:UTF-8>
>> CharDet.detect(str)
=> {"encoding"=>"GB2312", "confidence"=>0.99}
>> str.force_encoding('GB2312').valid_encoding?
=> false
>> str.force_encoding('GB18030').valid_encoding?
=> true
```

From [wikipedia](https://en.wikipedia.org/wiki/GB_2312):

> GB2312 (1980) has been superseded by GBK and [GB18030](https://en.wikipedia.org/wiki/GB_18030)...

I'm not an authority on encodings, but I did see that the C++ port [uchardet](https://github.com/BYVoid/uchardet) similarly [replaces all references to GB2312 with GB18030](https://github.com/BYVoid/uchardet/search?q=gb18030).

### CODE REVIEW

**Comment by grosser** [comment]
tests are failing :)

**Comment by grosser** [comment]
seems reasonable to me ... will merge on green +24h unless anyone complains ...

/cc @jmhodges @KitaitiMakoto

**Comment by rlue** [comment]
Whoa, so fast!

Tests are now passing! Quick question, though — currently, all the sample XML files used for testing this encoding specify the following (or similar) on their first line:

```xml
<?xml version="1.0" encoding="gb2312"?>
```

Of course, since one is a subset of the other, this is technically correct, and it's equally correct for `CharDet` to return `{ "encoding" => "GB18030" }`, but it's also potentially confusing.

1. Should I add a note about this in the comments somewhere, to avoid confusion for future contributors?
2. Do you want me to add GB18030-encoded XML files to the `/test/assets` directory?

My preference on both points is to not undertake any additional work, mostly because I'm lazy. I'm more than happy to oblige the maintainers if they'd like to see these things happen, though.

**Comment by rlue** [comment]
Also, will you be pushing the new release to rubygems.org after the merge? It'd really help out a project I'm working on :)

**Comment by KitaitiMakoto** [comment]
Thank you for the mention.

But I have no idea about this pull request because I'm not familiar with Chinese encodings.

**Comment by grosser** [comment]
1.8.0

**Pull request merged**
